// Ghost — RAG Memory Engine using ObjectBox.

import 'dart:convert';
import 'dart:io';
import 'package:logging/logging.dart';
// ignore: unnecessary_import
import 'package:objectbox/objectbox.dart';
import 'dart:math' as math;
import 'package:uuid/uuid.dart';
import 'package:path/path.dart' as p;
import 'package:syncfusion_flutter_pdf/pdf.dart';

import 'providers/factory.dart';
import '../config/config.dart';
import '../config/secure_storage.dart';
import '../models/provider.dart';

// Note: objectbox.g.dart is generated by build_runner.
import '../../objectbox.g.dart';

final _log = Logger('Ghost.RAGMemory');

@Entity()
class RAGChunk {
  RAGChunk({
    this.obxId = 0,
    required this.uuid,
    required this.text,
    required this.metadataJson,
    this.embedding,
  });

  @Id()
  int obxId = 0; // ObjectBox auto-increment ID

  // A stable UUID across backups/imports.
  @Unique()
  String uuid;

  String text;
  String metadataJson;

  @Property(type: PropertyType.floatVector)
  List<double>? embedding;

  @Transient()
  Map<String, dynamic> get metadata => jsonDecode(metadataJson) as Map<String, dynamic>;
  set metadata(Map<String, dynamic> value) => metadataJson = jsonEncode(value);
}

/// A RAG-based alternative to the standard keyword memory engine.
/// Uses ObjectBox for local storage and optional vector search.
class RAGMemoryEngine {
  RAGMemoryEngine({
    required this.config,
    required this.stateDir,
    required this.storage,
  });

  MemoryConfig config;
  final String stateDir;
  final SecureStorage storage;

  Store? _store;
  Box<RAGChunk>? _box;
  bool _initialized = false;
  bool _syncing = false;
  
  final _uuid = const Uuid();

  /// Initialize the ObjectBox store.
  Future<void> initialize() async {
    if (_initialized) return;

    try {
      _store = await openStore(directory: '$stateDir/objectbox_rag');
      _box = _store!.box<RAGChunk>();
      _initialized = true;
      _log.info('RAG Memory initialized at $stateDir/objectbox_rag');
    } catch (e) {
      _log.severe('Failed to initialize RAG Memory (ObjectBox): $e');
    }
  }

  /// Close the ObjectBox store.
  Future<void> close() async {
    _store?.close();
    _store = null;
    _box = null;
    _initialized = false;
  }

  /// Update configuration.
  void updateConfig(MemoryConfig newConfig) {
    config = newConfig;
  }

  /// Helper to get the embedding provider based on config.
  Future<AIModelProvider?> _getEmbeddingProvider() async {
    if (!config.ragEnabled) return null;
    final configProviderId = config.embeddingProvider;
    final configModel = config.embeddingModel;
    if (configProviderId.isEmpty || configModel.isEmpty) {
      _log.warning('No embedding provider/model configured for RAG.');
      return null;
    }
    try {
      return await ProviderFactory.create(
        model: configModel,
        provider: configProviderId,
        storage: storage,
      );
    } catch (e) {
      _log.warning('Could not create embedding provider: $e');
    }
    return null;
  }

  /// Add a generic text fact. It will be embedded.
  Future<void> add(String text, {Map<String, dynamic> metadata = const {}, AIModelProvider? testProvider}) async {
    final provider = testProvider ?? await _getEmbeddingProvider();
    if (provider == null) {
      _log.warning('No embedding provider available, cannot add to RAG memory.');
      return;
    }

    final chunks = _chunkText(text, config.chunkSize, config.chunkOverlap);
    for (final chunkText in chunks) {
      try {
        final embedding = await provider.embed(chunkText, model: config.embeddingModel);
        final chunk = RAGChunk(
          uuid: _uuid.v4(),
          text: chunkText,
          metadataJson: jsonEncode(metadata),
          embedding: embedding,
        );
        _box?.put(chunk);
      } catch (e) {
        _log.warning('Failed to generate embedding for RAG chunk: $e');
      }
    }
  }

  /// Query the vector store.
  Future<List<String>> query(String queryText, {String? category, AIModelProvider? testProvider}) async {
    final provider = testProvider ?? await _getEmbeddingProvider();
    if (provider == null || _box == null) return [];

    try {
      _log.fine('RAG query using provider: ${provider.providerId}, model: ${config.embeddingModel}');
      final queryEmbedding = await provider.embed(queryText, model: config.embeddingModel);
      
      final queryBoxResult = _box!.getAll();
      
      final candidates = queryBoxResult.where((c) {
        if (category == null) return true;
        return c.metadata['category'] == category;
      }).toList();

      if (candidates.isEmpty) return [];

      final scored = candidates.map((c) {
        final score = _cosineSimilarity(queryEmbedding, c.embedding ?? []);
        return MapEntry(c, score);
      }).toList();

      scored.sort((a, b) => b.value.compareTo(a.value));

      return scored
          .where((e) => e.value > 0.5)
          .take(5)
          .map((e) => e.key.text)
          .toList();

    } catch (e) {
      _log.warning('RAG query failed: $e');
      return [];
    }
  }

  List<String> _chunkText(String text, int size, int overlap) {
    if (text.isEmpty) return [];
    if (text.length <= size) return [text];
    
    final chunks = <String>[];
    int start = 0;
    while (start < text.length) {
      final end = math.min(start + size, text.length);
      chunks.add(text.substring(start, end));
      if (end == text.length) break;
      start += (size - overlap);
    }
    return chunks;
  }

  double _cosineSimilarity(List<double> a, List<double> b) {
    if (a.isEmpty || b.isEmpty || a.length != b.length) return 0.0;
    double dotProduct = 0.0;
    double normA = 0.0;
    double normB = 0.0;
    for (int i = 0; i < a.length; i++) {
      dotProduct += a[i] * b[i];
      normA += math.pow(a[i], 2);
      normB += math.pow(b[i], 2);
    }
    if (normA == 0.0 || normB == 0.0) return 0.0;
    return dotProduct / (math.sqrt(normA) * math.sqrt(normB));
  }

  Future<String> backup() async {
    if (_box == null) return '[]';
    final allChunks = _box!.getAll();
    final jsonList = allChunks.map((c) => {
      'uuid': c.uuid,
      'text': c.text,
      'metadataJson': c.metadataJson,
      'embedding': c.embedding,
    }).toList();
    return jsonEncode(jsonList);
  }

  Future<void> restore(String jsonData) async {
    if (_box == null) return;
    try {
      final jsonList = jsonDecode(jsonData) as List<dynamic>;
      _box!.removeAll();
      final chunks = jsonList.map((item) => RAGChunk(
        uuid: item['uuid'] as String,
        text: item['text'] as String,
        metadataJson: item['metadataJson'] as String? ?? '{}',
        embedding: (item['embedding'] as List<dynamic>?)?.map((e) => (e as num).toDouble()).toList(),
      )).toList();
      _box!.putMany(chunks);
      _log.info('Restored ${chunks.length} chunks to RAG memory');
    } catch (e) {
      _log.severe('RAG Restore failed: $e');
      throw Exception('Failed to restore RAG memory backup: $e');
    }
  }

  /// Delete all stored RAG chunks.
  Future<void> clear() async {
    if (_box == null) return;
    _box!.removeAll();
    _log.info('Cleared all chunks from RAG memory');
  }

  Future<void> syncWorkspaceRag(String workspacePath, {AIModelProvider? testProvider}) async {
    if (!config.ragEnabled || !config.workspaceRagEnabled || !_initialized) {
      // If RAG is disabled or workspace RAG is disabled, clean up indexed chunks from workspace
      _cleanAllWorkspaceRagChunks();
      return;
    }

    if (_syncing) {
      _log.info('Workspace RAG sync already in progress. Skipping.');
      return;
    }

    _syncing = true;
    try {
      final ragDir = Directory(p.join(workspacePath, 'rag'));
      if (!await ragDir.exists()) {
        _log.info('RAG directory does not exist in workspace: ${ragDir.path}');
        _cleanAllWorkspaceRagChunks();
        return;
      }

      final files = <File>[];
      await for (final entity in ragDir.list(recursive: true)) {
        if (entity is File) {
          files.add(entity);
        }
      }

      final provider = testProvider ?? await _getEmbeddingProvider();
      if (provider == null) {
        _log.warning('No embedding provider available for RAG workspace sync.');
        return;
      }

      // Build maps of relative path -> lastModified (ms) and file size (bytes)
      final currentFilesMTime = <String, int>{};
      final currentFilesSize = <String, int>{};
      for (final file in files) {
        final relPath = p.relative(file.path, from: ragDir.path);
        // Skip hidden files/directories (starting with .)
        if (p.split(relPath).any((part) => part.startsWith('.'))) {
          continue;
        }
        try {
          final stat = await file.stat();
          currentFilesMTime[relPath] = stat.modified.millisecondsSinceEpoch;
          currentFilesSize[relPath] = stat.size;
        } catch (e) {
          _log.warning('Failed to stat file $relPath: $e');
        }
      }

      // Get all existing chunks for "workspace_rag" source
      final allChunks = _box!.getAll();
      final workspaceChunks = allChunks.where((c) {
        try {
          return c.metadata['source'] == 'workspace_rag';
        } catch (_) {
          return false;
        }
      }).toList();

      // Find the modified time of the files stored in the DB
      final dbFilesModifiedTime = <String, int>{};
      final chunksByFile = <String, List<RAGChunk>>{};
      for (final chunk in workspaceChunks) {
        final meta = chunk.metadata;
        final filePath = meta['filePath'] as String?;
        final modifiedTime = meta['modifiedTime'] as int?;
        if (filePath != null && modifiedTime != null) {
          chunksByFile.putIfAbsent(filePath, () => []).add(chunk);
          final currentMax = dbFilesModifiedTime[filePath] ?? 0;
          if (modifiedTime > currentMax) {
            dbFilesModifiedTime[filePath] = modifiedTime;
          }
        }
      }

      // Identify files to delete, update, or add
      final filesToDelete = <String>{};
      for (final dbFilePath in dbFilesModifiedTime.keys) {
        if (!currentFilesMTime.containsKey(dbFilePath)) {
          filesToDelete.add(dbFilePath);
        }
      }

      final filesToIndex = <Map<String, dynamic>>[];
      for (final entry in currentFilesMTime.entries) {
        final filePath = entry.key;
        final mTime = entry.value;
        final dbMTime = dbFilesModifiedTime[filePath];
        if (dbMTime == null || mTime != dbMTime) {
          final size = currentFilesSize[filePath] ?? 0;
          filesToIndex.add({
            'filePath': filePath,
            'mTime': mTime,
            'size': size,
          });
        }
      }

      // Sort files by size ascending (Shortest Job First)
      filesToIndex.sort((a, b) => (a['size'] as int).compareTo(b['size'] as int));

      // 1. Delete removed files
      if (filesToDelete.isNotEmpty) {
        _log.info('Deleting chunks for removed files: $filesToDelete');
        _cleanDeletedWorkspaceRagChunks(filesToDelete);
      }

      // 2. Index new/modified files (smallest first)
      for (final item in filesToIndex) {
        final filePath = item['filePath'] as String;
        final mTime = item['mTime'] as int;

        // Delete any existing chunks for this file first
        final existing = chunksByFile[filePath];
        if (existing != null && existing.isNotEmpty) {
          _box!.removeMany(existing.map((c) => c.obxId).toList());
        }

        final file = File(p.join(ragDir.path, filePath));
        _log.info('Indexing workspace RAG file: $filePath (Size: ${item['size']} bytes)');
        try {
          final text = await _extractTextFromFile(file);
          if (text.trim().isEmpty) continue;

          final chunks = _chunkText(text, config.chunkSize, config.chunkOverlap);
          for (final chunkText in chunks) {
            final embedding = await provider.embed(chunkText, model: config.embeddingModel);
            final chunk = RAGChunk(
              uuid: _uuid.v4(),
              text: chunkText,
              metadataJson: jsonEncode({
                'source': 'workspace_rag',
                'filePath': filePath,
                'modifiedTime': mTime,
              }),
              embedding: embedding,
            );
            _box!.put(chunk);
          }
        } catch (e) {
          _log.severe('Failed to index workspace file $filePath: $e');
        }
      }
    } catch (e) {
      _log.severe('Error during workspace RAG sync: $e');
    } finally {
      _syncing = false;
    }
  }

  Future<String> _extractTextFromFile(File file) async {
    final ext = p.extension(file.path).toLowerCase();
    if (ext == '.pdf') {
      try {
        final bytes = await file.readAsBytes();
        final document = PdfDocument(inputBytes: bytes);
        final extractor = PdfTextExtractor(document);
        final text = extractor.extractText();
        document.dispose();
        return text;
      } catch (e) {
        _log.warning('Failed to extract PDF text from ${file.path}: $e');
        return '';
      }
    }

    // List of allowed text extensions
    const textExtensions = {
      '.txt', '.md', '.markdown', '.json', '.csv', '.xml', 
      '.yaml', '.yml', '.html', '.htm', '.css', '.js', 
      '.ts', '.dart', '.py', '.sh', '.bat', '.ini', '.cfg'
    };

    if (ext.isNotEmpty && !textExtensions.contains(ext)) {
      _log.fine('Skipping non-text file extension: $ext for ${file.path}');
      return '';
    }

    try {
      return await file.readAsString(encoding: utf8);
    } catch (e) {
      _log.warning('Failed to read file as UTF-8 text ${file.path}: $e');
      return '';
    }
  }

  void _cleanAllWorkspaceRagChunks() {
    if (_box == null) return;
    final allChunks = _box!.getAll();
    final toDelete = <int>[];
    for (final chunk in allChunks) {
      try {
        final meta = chunk.metadata;
        if (meta['source'] == 'workspace_rag') {
          toDelete.add(chunk.obxId);
        }
      } catch (_) {}
    }
    if (toDelete.isNotEmpty) {
      _box!.removeMany(toDelete);
      _log.info('Removed all (${toDelete.length}) workspace RAG chunks');
    }
  }

  void _cleanDeletedWorkspaceRagChunks(Set<String> filesToDelete) {
    if (_box == null) return;
    final allChunks = _box!.getAll();
    final toDelete = <int>[];
    for (final chunk in allChunks) {
      try {
        final meta = chunk.metadata;
        if (meta['source'] == 'workspace_rag') {
          final filePath = meta['filePath'] as String?;
          if (filePath == null || filesToDelete.contains(filePath)) {
            toDelete.add(chunk.obxId);
          }
        }
      } catch (_) {}
    }
    if (toDelete.isNotEmpty) {
      _box!.removeMany(toDelete);
      _log.info('Removed ${toDelete.length} workspace RAG chunks');
    }
  }
}
