// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'engine/agent/rag_memory.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 7141642882014988805),
    name: 'RAGChunk',
    lastPropertyId: const obx_int.IdUid(5, 505725302784329942),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 8321140688701372340),
        name: 'obxId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2917475434088790853),
        name: 'uuid',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(1, 5891081993253487757),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 715869011206658204),
        name: 'text',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8992848763589166556),
        name: 'metadataJson',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 505725302784329942),
        name: 'embedding',
        type: 28,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(1, 7141642882014988805),
    lastIndexId: const obx_int.IdUid(1, 5891081993253487757),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    RAGChunk: obx_int.EntityDefinition<RAGChunk>(
      model: _entities[0],
      toOneRelations: (RAGChunk object) => [],
      toManyRelations: (RAGChunk object) => {},
      getId: (RAGChunk object) => object.obxId,
      setId: (RAGChunk object, int id) {
        object.obxId = id;
      },
      objectToFB: (RAGChunk object, fb.Builder fbb) {
        final uuidOffset = fbb.writeString(object.uuid);
        final textOffset = fbb.writeString(object.text);
        final metadataJsonOffset = fbb.writeString(object.metadataJson);
        final embeddingOffset = object.embedding == null
            ? null
            : fbb.writeListFloat32(object.embedding!);
        fbb.startTable(6);
        fbb.addInt64(0, object.obxId);
        fbb.addOffset(1, uuidOffset);
        fbb.addOffset(2, textOffset);
        fbb.addOffset(3, metadataJsonOffset);
        fbb.addOffset(4, embeddingOffset);
        fbb.finish(fbb.endTable());
        return object.obxId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final obxIdParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final uuidParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final textParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final metadataJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final embeddingParam = const fb.ListReader<double>(
          fb.Float32Reader(),
          lazy: false,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final object = RAGChunk(
          obxId: obxIdParam,
          uuid: uuidParam,
          text: textParam,
          metadataJson: metadataJsonParam,
          embedding: embeddingParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [RAGChunk] entity fields to define ObjectBox queries.
class RAGChunk_ {
  /// See [RAGChunk.obxId].
  static final obxId = obx.QueryIntegerProperty<RAGChunk>(
    _entities[0].properties[0],
  );

  /// See [RAGChunk.uuid].
  static final uuid = obx.QueryStringProperty<RAGChunk>(
    _entities[0].properties[1],
  );

  /// See [RAGChunk.text].
  static final text = obx.QueryStringProperty<RAGChunk>(
    _entities[0].properties[2],
  );

  /// See [RAGChunk.metadataJson].
  static final metadataJson = obx.QueryStringProperty<RAGChunk>(
    _entities[0].properties[3],
  );

  /// See [RAGChunk.embedding].
  static final embedding = obx.QueryDoubleVectorProperty<RAGChunk>(
    _entities[0].properties[4],
  );
}
