// Ghost — RAG Memory Engine using ObjectBox.

import 'dart:convert';
import 'package:logging/logging.dart';
// ignore: unnecessary_import
import 'package:objectbox/objectbox.dart';
import 'dart:math' as math;
import 'package:uuid/uuid.dart';

import 'providers/factory.dart';
import '../config/config.dart';
import '../config/secure_storage.dart';
import '../models/provider.dart';

// Note: objectbox.g.dart is generated by build_runner.
import '../objectbox.g.dart';

final _log = Logger('Ghost.RAGMemory');

@Entity()
class RAGChunk {
  RAGChunk({
    this.obxId = 0,
    required this.uuid,
    required this.text,
    required this.metadataJson,
    this.embedding,
  });

  @Id()
  int obxId = 0; // ObjectBox auto-increment ID

  // A stable UUID across backups/imports.
  @Unique()
  String uuid;

  String text;
  String metadataJson;

  @Property(type: PropertyType.floatVector)
  List<double>? embedding;

  @Transient()
  Map<String, dynamic> get metadata => jsonDecode(metadataJson) as Map<String, dynamic>;
  set metadata(Map<String, dynamic> value) => metadataJson = jsonEncode(value);
}

/// A RAG-based alternative to the standard keyword memory engine.
/// Uses ObjectBox for local storage and optional vector search.
class RAGMemoryEngine {
  RAGMemoryEngine({
    required this.config,
    required this.stateDir,
    required this.storage,
  });

  MemoryConfig config;
  final String stateDir;
  final SecureStorage storage;

  Store? _store;
  Box<RAGChunk>? _box;
  bool _initialized = false;
  
  final _uuid = const Uuid();

  /// Initialize the ObjectBox store.
  Future<void> initialize() async {
    if (_initialized) return;

    try {
      _store = openStore(directory: '$stateDir/objectbox_rag');
      _box = _store!.box<RAGChunk>();
      _initialized = true;
      _log.info('RAG Memory initialized at $stateDir/objectbox_rag');
    } catch (e) {
      _log.severe('Failed to initialize RAG Memory (ObjectBox): $e');
    }
  }

  /// Close the ObjectBox store.
  Future<void> close() async {
    _store?.close();
    _store = null;
    _box = null;
    _initialized = false;
  }

  /// Update configuration.
  void updateConfig(MemoryConfig newConfig) {
    config = newConfig;
  }

  /// Helper to get the embedding provider based on config.
  Future<AIModelProvider?> _getEmbeddingProvider() async {
    if (!config.ragEnabled) return null;
    final configProviderId = config.embeddingProvider;
    final configModel = config.embeddingModel;
    if (configProviderId.isEmpty || configModel.isEmpty) {
      _log.warning('No embedding provider/model configured for RAG.');
      return null;
    }
    try {
      return await ProviderFactory.create(
        model: configModel,
        provider: configProviderId,
        storage: storage,
      );
    } catch (e) {
      _log.warning('Could not create embedding provider: $e');
    }
    return null;
  }

  /// Add a generic text fact. It will be embedded.
  Future<void> add(String text, {Map<String, dynamic> metadata = const {}, AIModelProvider? testProvider}) async {
    final provider = testProvider ?? await _getEmbeddingProvider();
    if (provider == null) {
      _log.warning('No embedding provider available, cannot add to RAG memory.');
      return;
    }

    final chunks = _chunkText(text, config.chunkSize, config.chunkOverlap);
    for (final chunkText in chunks) {
      try {
        final embedding = await provider.embed(chunkText, model: config.embeddingModel);
        final chunk = RAGChunk(
          uuid: _uuid.v4(),
          text: chunkText,
          metadataJson: jsonEncode(metadata),
          embedding: embedding,
        );
        _box?.put(chunk);
      } catch (e) {
        _log.warning('Failed to generate embedding for RAG chunk: $e');
      }
    }
  }

  /// Query the vector store.
  Future<List<String>> query(String queryText, {String? category, AIModelProvider? testProvider}) async {
    final provider = testProvider ?? await _getEmbeddingProvider();
    if (provider == null || _box == null) return [];

    try {
      _log.fine('RAG query using provider: ${provider.providerId}, model: ${config.embeddingModel}');
      final queryEmbedding = await provider.embed(queryText, model: config.embeddingModel);
      
      final queryBoxResult = _box!.getAll();
      
      final candidates = queryBoxResult.where((c) {
        if (category == null) return true;
        return c.metadata['category'] == category;
      }).toList();

      if (candidates.isEmpty) return [];

      final scored = candidates.map((c) {
        final score = _cosineSimilarity(queryEmbedding, c.embedding ?? []);
        return MapEntry(c, score);
      }).toList();

      scored.sort((a, b) => b.value.compareTo(a.value));

      return scored
          .where((e) => e.value > 0.5)
          .take(5)
          .map((e) => e.key.text)
          .toList();

    } catch (e) {
      _log.warning('RAG query failed: $e');
      return [];
    }
  }

  List<String> _chunkText(String text, int size, int overlap) {
    if (text.isEmpty) return [];
    if (text.length <= size) return [text];
    
    final chunks = <String>[];
    int start = 0;
    while (start < text.length) {
      final end = math.min(start + size, text.length);
      chunks.add(text.substring(start, end));
      if (end == text.length) break;
      start += (size - overlap);
    }
    return chunks;
  }

  double _cosineSimilarity(List<double> a, List<double> b) {
    if (a.isEmpty || b.isEmpty || a.length != b.length) return 0.0;
    double dotProduct = 0.0;
    double normA = 0.0;
    double normB = 0.0;
    for (int i = 0; i < a.length; i++) {
      dotProduct += a[i] * b[i];
      normA += math.pow(a[i], 2);
      normB += math.pow(b[i], 2);
    }
    if (normA == 0.0 || normB == 0.0) return 0.0;
    return dotProduct / (math.sqrt(normA) * math.sqrt(normB));
  }

  Future<String> backup() async {
    if (_box == null) return '[]';
    final allChunks = _box!.getAll();
    final jsonList = allChunks.map((c) => {
      'uuid': c.uuid,
      'text': c.text,
      'metadataJson': c.metadataJson,
      'embedding': c.embedding,
    }).toList();
    return jsonEncode(jsonList);
  }

  Future<void> restore(String jsonData) async {
    if (_box == null) return;
    try {
      final jsonList = jsonDecode(jsonData) as List<dynamic>;
      _box!.removeAll();
      final chunks = jsonList.map((item) => RAGChunk(
        uuid: item['uuid'] as String,
        text: item['text'] as String,
        metadataJson: item['metadataJson'] as String? ?? '{}',
        embedding: (item['embedding'] as List<dynamic>?)?.map((e) => (e as num).toDouble()).toList(),
      )).toList();
      _box!.putMany(chunks);
      _log.info('Restored ${chunks.length} chunks to RAG memory');
    } catch (e) {
      _log.severe('RAG Restore failed: $e');
      throw Exception('Failed to restore RAG memory backup: $e');
    }
  }

  /// Delete all stored RAG chunks.
  Future<void> clear() async {
    if (_box == null) return;
    _box!.removeAll();
    _log.info('Cleared all chunks from RAG memory');
  }
}
